spring:
  datasource:
    url: jdbc:mysql://localhost:3306/woniubookshop03?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 10
      maxActive: 30
      minIdle: 5
      maxWait: 2000
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

mybatis-plus:
  # mapper.xml 文件路径
  mapper-locations: classpath*:/mapper/**/*.xml
  # type的默认包前缀
  type-aliases-package: com.woniuxy
  # 配置项
  configuration:
    # 是否将下画线自动转换为驼峰,一般指定为false
    map-underscore-to-camel-case: false
    # 为了在执行时打印出sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
